spacetelescope/jwst_validation_notebooks

Jenkinsfile

Removing my username and replacing it with `spacetelescope`

Jenkins Build For Notebooks

---

jwst_validation_notebooks/resample/jwst_resample_miri_test/jwst_resample_miri_testing.ipynb

The resample notebook was updated to take in an association file, run data through calwebb_image3 and use regtest to pull files from artifactory.

Updated resample notebook, uses regtest

---

Jenkinsfile

Adding missing { as well as other shell command that I removed by accident. Also adding the rsync commands to copy over the html files.

Bug fix for Jenkinsfile

---

Jenkinsfile
requirements.txt

Adding report flag to convert in Jenkinsfile and junit-xml to requirements.

More updates to Jenkinsfile

---

Jenkinsfile

Removing `mfixstsci` and replacing it with `spacetelescope`.

Replacing old repo with spacetelescope

---

jwst_validation_notebooks/calwebb_detector1/jwst_detector1_miri_test/jwst_detector1_miri_imtso_testing.ipynb

First commit of TSO imaging detector1 notebook for MIRI

Adding tso detector1 imaging notebook

---

README.md
jwst_validation_notebooks/templates/jwst_validation_notebook_template.ipynb

Updated the instructions in the README and the template notebook to say that a Jira Task issue should be filed to request data get added to artifactory, not a github issue.

Fixed the statement about filing a github issue

---

jwst_validation_notebooks/jump/jwst_jump_miri_test/jwst_jump_miri_testing.ipynb
jwst_validation_notebooks/resample/jwst_resample_miri_test/jwst_resample_miri_testing.ipynb
jwst_validation_notebooks/reset/jwst_reset_miri_test/jwst_reset_miri_testing.ipynb
jwst_validation_notebooks/rscd/jwst_rscd_miri_test/jwst_miri_rscd_testing.ipynb
jwst_validation_notebooks/source_catalog/jwst_source_catalog_miri_test/jwst_source_catalog_miri_test.ipynb

Updating how files are read in to notebooks.

Updating reading in files

---

jwst_validation_notebooks/calwebb_coron3/MIRI_shared_calcoron3_testing.ipynb
jwst_validation_notebooks/calwebb_coron3/test.yml

Jupyter notebook and corresponding .yml file for testing the calwebb_coron3 pipeline on MIRI simulated data.

MIRI calwebb_coron3 testing

---

.gitignore
.travis.yml
base/index.tpl
base/nb_html.tpl
convert.py
environment.yml

Hopefully this will solve the Jenkins error of not being able to locate the template. Can't do local testing because, for whatever reason, there is no version of the "nbpages" package on pip that actually is usable in the way that convert.py uses it.

changed convert.py to use absolute path

---

JenkinsfileDeploy
convert.py
environment.yml

Setting needed environment variables when creating conda environment.

Set environment variables in creating conda environment

---

JenkinsfileDeploy

Modified jenkins so that it will hopefully sync HTML files regardless of their depth in directories.

Changed Jenkins to hopefully include all the HTML files

---

jwst_validation_notebooks/flat_field/jwst_flat_field_miri_test/jwst_flat_field_miri_test.ipynb

Update the flat field notebook to no longer use the "with" statement to open files (and thus let the open file go out of scope) but instead to create an ImageModel directly.

Update flat field notebook to proper file open format

---

jwst_validation_notebooks/photom/jwst_photom_miri_test/jwst_photom_miri_test.ipynb

Fixes problems with photom notebook

Updated photom notebook

---

README.md
environment.yml

Updated the readme file to include creating a test environment, as well as additional links.

Updated README.md for current flow

---

JenkinsfileDeploy

Because requirements.txt was removed in favor of environment.yml, removed the jenkins call to requirements.txt.

Removed explicit call to requirements.txt

---

.github/workflows/ci_workflows.yml
environment.yml

Update nirspec_pipe_testing_tool to 1.1.3

---

README.md

Fixed a typo in box links, and added a link on getting static Box links

---

environment.yml

Added pytest, pytest-xdist, pytest-html to environment.yml.

Adding pytest to environment.yml

---

convert.py
environment.yml

Updated environment to use my nbpages fork that the run timeout to be set. And then updates convert.py to do the setting.

Updated environment to use my fork of nbpages, and convert to set a manual run timeout.

---

jwst_validation_notebooks/source_catalog/jwst_source_catalog_miri_test/jwst_source_catalog_miri_test.ipynb

Fixed issues with source_catalog notebook

updating source_catalog test

---

.github/workflows/ci_workflows.yml
JenkinsfileDeploy
jwst_validation_notebooks/calwebb_coron3/jwst_calcoron3_miri_test.ipynb
jwst_validation_notebooks/calwebb_coron3/jwst_calcoron3_miri_test.yml
jwst_validation_notebooks/image3/jwst_image3_miri_test/jwst_image3_miri_test.ipynb
jwst_validation_notebooks/skymatch/jwst_skymatch_miri_test/jwst_skymatch_miri_test.ipynb

Fixed a file accidentally deleted, and fixed the jenkins deploy to no longer be trying to load outdated packages.

Jenkins Fixes

---

convert.py

Hopefully this will let them complete.

increased notebook timeout value

---

jwst_validation_notebooks/background/jwst_background_miri_test/background_sub-miri-lrs-slit.ipynb

Adding MIRI LRS background subtraction notebook.

Adding background notebook

---

jwst_validation_notebooks/outlier_detection/jwst_outlier_detection_miri_test/jwst_outlier_detection_view_miri_test.ipynb

Adding new outlier detection notebook.

Adding notebook to view outlier_detection

---

environment.yml

This is to support the next testing round.

Updated environment.yml to include and be compatible with jwst version 1.1.0

---

jwst_validation_notebooks/resample/jwst_resample_miri_test/jwst_resample_miri_testing.ipynb

Needed to update the input files to the resample test to use the updated flat files in the input cal files.

updated resample input files and names

---

jwst_validation_notebooks/resample/jwst_resample_miri_test/jwst_resample_miri_testing.ipynb

Previous plot missed most data points. Updated range to plot.

updated plot range for resample test

---

jwst_validation_notebooks/source_catalog/jwst_source_catalog_miri_test/jwst_source_catalog_miri_test.ipynb

Changed y axis orientation and scaling of image display in notebook.

Updated display on source_catalog notebook

---

jwst_validation_notebooks/flat_field/jwst_flat_field_miri_test/jwst_flat_field_miri_test.ipynb

Added DQ test and cleaned up import statement section in flat_field notebook.

Added DQ test to flat_field notebook

---

jwst_validation_notebooks/resample/jwst_resample_miri_test/jwst_resample_miri_testing.ipynb

Adding scaling test of 'ratio' parameter to resample notebook.

Adding ratio scaled test to resample

---

jwst_validation_notebooks/assign_wcs/jwst_assign_wcs_miri_test/assign_wcs-miri-mrs.ipynb

Added temporary directory info to the mrs assign_wcs notebook.

Added temp dir info

---

jwst_validation_notebooks/assign_wcs/jwst_assign_wcs_miri_test/assign_wcs-miri-mrs.ipynb
jwst_validation_notebooks/calwebb_coron3/jwst_calcoron3_nircam_test.ipynb
jwst_validation_notebooks/image3/jwst_image3_miri_test/jwst_image3_miri_test.ipynb
jwst_validation_notebooks/outlier_detection/jwst_outlier_detection_miri_test/jwst_outlier_detection_miri_test.ipynb
jwst_validation_notebooks/photom/jwst_photom_miri_test/jwst_photom_miri_test.ipynb
jwst_validation_notebooks/skymatch/jwst_skymatch_miri_test/jwst_skymatch_miri_test.ipynb
jwst_validation_notebooks/source_catalog/jwst_source_catalog_miri_test/jwst_source_catalog_miri_test.ipynb

Cleaning up titles across notebooks. Also made small edits to the image3 notebook.

Standardizing notebook titles

---

README.md

@cracraft @york-stsci 
I created a draft of our Box workflow using the information that Hsing-Ying Liu provided to us this morning. Let me know if this looks okay (or feel free to suggest changes!).

Updating README with new Box instructions

---

README.md

The instructions might have caused people to have unclosed files, so I fixed the instructions in the Box part. No other change.

Fixed instructions to remove open file

---

jwst_validation_notebooks/resample/jwst_resample_miri_test/jwst_resample_miri_testing.ipynb

Removed call to specific crds context, added a couple more plots and stats to check that step works.

Updating resample notebook with new plots

---

jwst_validation_notebooks/flat_field/jwst_flat_field_miri_test/jwst_flat_field_miri_test.ipynb

Making updates to MIRI Imaging flat_field notebook based on feedback by MIRI team.

Updating Imaging flat_field notebook

---

jwst_validation_notebooks/cube_build/jwst_cube_build_miri_test/testing_point_source_flux_conservation_modeshep_all.ipynb

Zero padded filenames due to updated secondary code repo.

updated filenames in notebook

---

jwst_validation_notebooks/assign_wcs/jwst_assign_wcs_niriss_test/jwst_assign_wcs_niriss_image.ipynb
jwst_validation_notebooks/calwebb_detector1/jwst_detector1_miri_test/caldetector1-miri-lrs-tso.ipynb
jwst_validation_notebooks/cube_build/jwst_cube_build_miri_test/test_cube_build_spec3.ipynb
jwst_validation_notebooks/dark_current/jwst_dark_current_unit_tests.ipynb
jwst_validation_notebooks/dq_init/jwst_dq_init_unit_tests.ipynb
jwst_validation_notebooks/firstframe/jwst_firstframe_unit_tests.ipynb
jwst_validation_notebooks/ipc/jwst_ipc_unit_tests.ipynb
jwst_validation_notebooks/jump/jwst_jump_unit_tests.ipynb
jwst_validation_notebooks/lastframe/jwst_lastframe_unit_tests.ipynb
jwst_validation_notebooks/linearity/jwst_linearity_unit_tests.ipynb
jwst_validation_notebooks/persistence/jwst_persistence_unit_tests.ipynb
jwst_validation_notebooks/ramp_fitting/jwst_ramp_fitting_unit_tests.ipynb
jwst_validation_notebooks/refpix/jwst_refpix_unit_tests.ipynb
jwst_validation_notebooks/rscd/jwst_rscd_unit_tests.ipynb
jwst_validation_notebooks/saturation/jwst_saturation_unit_tests.ipynb
jwst_validation_notebooks/source_catalog/jwst_source_catalog_nircam_test/jwst_nircam_imaging_source_catalog.ipynb
jwst_validation_notebooks/superbias/jwst_superbias_unit_tests.ipynb

Updating titles to show full information on title line of output webpage

Updated titles for notebooks

---

jwst_validation_notebooks/cube_build/jwst_cube_build_miri_test/test_cube_build_spec3.ipynb

Attempting to fix issue with notebook where title is not recognized by Jenkins process and notebook does not display in output web pages.

Fixing title issue

---

jwst_validation_notebooks/flat_field/jwst_flat_field_miri_test/flat_miri_mrs_test.ipynb

Moved title cell to the top of the notebook to enable linking in output webpage.

Moved title to first cell

---

environment.yml

Also re-organizes the environment.yml file a bit to remove duplicate entries and download from pip instead of GitHub where possible.

Update pipeline version to 1.2.3

---

jwst_validation_notebooks/source_catalog/jwst_source_catalog_nircam_test/jwst_nircam_imaging_source_catalog.ipynb

Updated notebook to reflect changes in column names in output catalog from 'id' to 'label'.

Updating id to label in catalog output

---

jwst_validation_notebooks/resample/jwst_resample_miri_test/jwst_resample_miri_lrs_slit.ipynb

this is a test notebook for the Spec3 resample step, for MIRI LRS (slit mode).

first version of resample notebook for miri lrs slit

---

jwst_validation_notebooks/background/jwst_background_miri_test/jwst_background_subtraction_miri_imaging_testing.ipynb

New MIRI background subtraction notebook for imaging

Adding new background sub notebook for imaging

---

jwst_validation_notebooks/pathloss/jwst_pathloss_nirspec_test/jwst_pathloss_nirspec_test.ipynb

fixed the source type bug and the summary output.

fixed the source_type bug

---

jwst_validation_notebooks/source_catalog/jwst_source_catalog_miri_test/jwst_source_catalog_miri_test.ipynb

Modify tests after update to source catalog output file.

Update source_catlog with to add tests

---

jwst_validation_notebooks/ami3/ami_average.ipynb

Updated first cell of notebook to have it display properly in the output webpage.

update intro section of ami notebook

---

jwst_validation_notebooks/jump/jwst_jump_miri_test/jwst_jump_miri_testing.ipynb

Jump step updated to run on 3 and 4 group integrations. Added test to the jump step testing to make sure not all pixels are flagged as jumps.

Add test for 3 and 4 group integrations

---

jwst_validation_notebooks/ami3/ami_normalize.ipynb

Adding ami_normalize in a clean branch so that it doesn't overwrite ami_average.

Adding ami_normalize notebook

---

jwst_validation_notebooks/calwebb_detector1/jwst_detector1_nircam_test/jwst_detector1_nircam_test.ipynb

Adding NIRCam detector1 notebook. This will close out PR163 that had a crash in the notebook while testing with convert.py.

Adding Nircam detector1 notebook

---

jwst_validation_notebooks/calwebb_image2/jwst_image2_nircam_test/jwst_image2_nircam_test.ipynb

Adding the NIRCam calwebb_image2 notebook to remove the with statements that were causing a crash.

Adding Nircam image2 notebook

---

environment.yml

Edited environment.yml to remove unnecessary module installs and version specifications

---

environment.yml

Updating photutils version in env file because photutils version 1.2.0 breaks jwst.

updating photutils version

---

environment.yml

Re-specifying the version of the nptt tool that should be used.

Update to specify nptt version

---

environment.yml

Update jwst code version to match build 7.8.2.

Updating jwst version

---

jwst_validation_notebooks/calwebb_coron3/jwst_calcoron3_miri_test.ipynb

These commits contain changes to the output plots to remove dependence on interactive widgets, and are up to date with the latest pull request from the base repo. @york-stsci @cracraft

Calwebb coron3 cube display

---

jwst_validation_notebooks/skymatch/jwst_skymatch_miri_test/jwst_skymatch_miri_test.ipynb

Adding tests of resample with skymatch to see how both steps work together.

Updated skymatch notebook

---

jwst_validation_notebooks/skymatch/jwst_skymatch_miri_test/jwst_skymatch_photom_miri_test.ipynb

Adding a notebook to test skymatch with sources and perform photometry.

Adding skymatch test with photometry

---

base/index.tpl
index.tpl

Adds a "generated on" timestamp to the index.html webpage.

Add timestamp to index.html

---

JenkinsfileDeploy

Modify the build order so that the website is updated before it's archived.

Make archival happen *after* website update

---

environment.yml

Update astropy to a version lower than 5 to hopefully sidestep a weird issue.

Update astropy version

---

JenkinsfileDeploy

Hopefully this lets the webpage archiving work.

Moved archive step to be in the correct directory

---

environment.yml

Update the JWST Build to 7.9.1 in the environment file.

Update to build 7.9.1

---

jwst_validation_notebooks/assign_wcs/jwst_assign_wcs_nirspec_test/jwst_assign_wcs_nirspec_test.ipynb
jwst_validation_notebooks/barshadow/jwst_barshadow_nirspec_test/jwst_barshadow_nirspec_test.ipynb

the assign_wcs notebook appears as modified because I opened it but I actually did not modify anything in it.

fixed bug in barshadow noteboook

---

jwst_validation_notebooks/photom/jwst_photom_miri_test/photom_miri_lrs_slit.ipynb

Put assert statements into try/except blocks to keep an assert failure from stopping the rest of the notebook.

put assert into try except blocks

---

jwst_validation_notebooks/assign_wcs/jwst_assign_wcs_miri_test/assign_wcs-miri-lrs-slit.ipynb
jwst_validation_notebooks/assign_wcs/jwst_assign_wcs_miri_test/assign_wcs-miri-lrs-tso.ipynb
jwst_validation_notebooks/background/jwst_background_miri_test/background_sub-miri-lrs-slit.ipynb
jwst_validation_notebooks/calwebb_detector1/jwst_detector1_miri_test/caldetector1-miri-lrs-tso.ipynb
jwst_validation_notebooks/extract_1d/jwst_extract_1d_miri_test/extract_1d-spec2-miri-lrs-slit.ipynb
jwst_validation_notebooks/extract_1d/jwst_extract_1d_miri_test/extract_1d-spec2-miri-lrs-slitless.ipynb
jwst_validation_notebooks/flat_field/jwst_flat_field_miri_test/flat-miri-lrs-slit.ipynb
jwst_validation_notebooks/flat_field/jwst_flat_field_miri_test/flat_miri_mrs_test.ipynb
jwst_validation_notebooks/flat_field/jwst_flat_field_miri_test/flatfield_analysis_slitless.ipynb
jwst_validation_notebooks/photom/jwst_photom_miri_test/photom_miri_lrs_slitless.ipynb

Put all assert statements into try/except blocks.

Updated assert statements

---

jwst_validation_notebooks/calwebb_image3/jwst_image3_miri_test/jwst_image3_miri_test.ipynb
jwst_validation_notebooks/outlier_detection/jwst_outlier_detection_miri_test/jwst_outlier_detection_view_miri_test.ipynb
jwst_validation_notebooks/resample/jwst_resample_miri_test/jwst_resample_miri_testing.ipynb
jwst_validation_notebooks/source_catalog/jwst_source_catalog_miri_test/jwst_source_catalog_miri_test.ipynb
jwst_validation_notebooks/tweakreg/jwst_tweakreg_miri_test/jwst_tweakreg_miri_test.ipynb

Updating image scaling for combined images out of calwebb_image3 now that resample is no longer subtracting the sky down to 0.

Updating image scaling

---

environment.yml

Update env file to pipeline version 8.0

update pipeline version

---

jwst_validation_notebooks/calwebb_detector1/jwst_detector1_miri_test/caldetector1-miri-lrs-tso.ipynb
jwst_validation_notebooks/calwebb_detector1/jwst_detector1_miri_test/jwst_detector1_miri_imtso_testing.ipynb
jwst_validation_notebooks/calwebb_detector1/jwst_detector1_nircam_test/jwst_detector1_nircam_test.ipynb
jwst_validation_notebooks/calwebb_image2/jwst_image2_nircam_test/jwst_image2_nircam_test.ipynb
jwst_validation_notebooks/calwebb_image3/jwst_image3_nircam_test/jwst_image3_nircam_test.ipynb
jwst_validation_notebooks/cube_build/jwst_cube_build_miri_test/test_cube_build_spec3.ipynb
jwst_validation_notebooks/flat_field/jwst_flat_field_miri_test/jwst_flat_field_miri_test.ipynb
jwst_validation_notebooks/outlier_detection/jwst_outlier_detection_miri_test/jwst_outlier_detection_view_miri_test.ipynb
jwst_validation_notebooks/outlier_detection/jwst_outlier_detection_miri_test/out_det_test2.ipynb
jwst_validation_notebooks/rscd/jwst_rscd_miri_test/jwst_miri_rscd_testing.ipynb
jwst_validation_notebooks/skymatch/jwst_skymatch_miri_test/jwst_skymatch_miri_test.ipynb
jwst_validation_notebooks/skymatch/jwst_skymatch_miri_test/jwst_skymatch_photom_miri_test.ipynb
jwst_validation_notebooks/source_catalog/jwst_source_catalog_miri_test/jwst_source_catalog_miri_test.ipynb
jwst_validation_notebooks/source_catalog/jwst_source_catalog_nircam_test/jwst_nircam_imaging_source_catalog.ipynb
jwst_validation_notebooks/tweakreg/jwst_tweakreg_miri_test/jwst_tweakreg_miri_test.ipynb

Updated notebooks that call data from box, adding a timeout of 600 seconds.

Update notebooks to add box timeouts

---

jwst_validation_notebooks/flat_field/jwst_flat_field_miri_test/jwst_flat_field_miri_test.ipynb

Added new unit test on dq flags to check that 'NO_FLAT_FIELD' is flagged 'DO_NOT_USE'

Added unit test on dq flags

---

jwst_validation_notebooks/resample/jwst_resample_miri_test/jwst_resample_miri_lrs_slit.ipynb

Updated title of resample notebook to clarify instrument and mode being tested.

Updated title of resample notebook

---

jwst_validation_notebooks/calwebb_image3/jwst_image3_miri_test/jwst_source_catalog_miri_gaia.ipynb

Add a new image3 notebook for MIRI using flight data and looking at Gaia catalog for comparison.

Add image3 notebook with flight data

---

jwst_validation_notebooks/tweakreg/jwst_tweakreg_miri_test/jwst_tweakreg_miri_test.ipynb

Updated variables from xcentroid and ycentroid to x and y to match output tables from image3 and allow notebook to run to completion.

Updated variable to allow notebook to run

---

jwst_validation_notebooks/background/jwst_background_miri_test/jwst_background_subtraction_miri_imaging_testing-flight.ipynb

Update the background subtraction notebook to use flight rather than simulated data.

Updated background subtraction to flight data

---

jwst_validation_notebooks/cube_build/jwst_cube_build_miri_test/test_cube_build_spec3.ipynb

Updated code to use str() rather than np.str() to avoid notebook crashing on error.

changed np.str to str to avoid error

---

environment.yml

Changed the NPTT version to the latest tag

updated nptt tag
